api:
  image: meetup/users-api
  ports:
   - "8080:8080"
  links:
    - activemq

handler:
  image: meetup/users-handler
  links:
    - activemq

activemq:
  image: cloudesire/activemq
  ports:
   - "8161:8161"
   - "61616:61616"
